#!/usr/bin/env node

const { argv: args } = require('yargs');
const repl = require('./index');
const locate = require('@giancarl021/locate');

const target = locate(args._[0], true);
const moduleName = args['module-name'] || args.m || 'm';

async function main() {
    if (!target) {
        throw new Error('No target specified');
    }

    await repl({
        target,
        moduleName
    });
}

main().catch(err => {
    console.error('Error: ' + err.message);
    process.exit(1);
});